### ISSUE TITLE
Add a CONTRIBUTING.md file?

### ISSUE THREAD

**Issue by kinow** [chchch/sanskrit-alignment#1]
Hi @chchch 

I'm reviewing the paper for sanskrit-alignment (helayo, and matrix-editor). Very interesting software!

See the [review issue](https://github.com/openjournals/joss-reviews/issues/4022) for what's being reviewed. This issue is about this item of the checklist:

>Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I think it's clear where users can report issues and seek support (over here, in the issues/pull requests sections I think).

However, there are no clear guidelines for third parties wishing to contribute to the software. Would you consider adding one? Regardless of the review requirements, I really think it could help other users wishing to contribute to your software in deciding whether to contribute or not.

- [Wrangling Web Contributions: How to Build a CONTRIBUTING.md](https://mozillascience.github.io/working-open-workshop/contributing/)
- [Adding a CONTRIBUTING file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file)

Cheers
-Bruno

**Comment by kinow** [comment]
@chchch I just rebased my local clone, and noticed you added a contributing file. I confirmed the file looks OK, and GH UI is already telling users about it :tada: 

![image](https://user-images.githubusercontent.com/304786/147295199-829313de-9b5a-4609-ab95-efd00df6bf6f.png)


Feel free to close this issue if you'd like (not sure if you were planning on writing more in that file.)

Thanks
-Bruno

**Comment by chchch** [comment]
I thought the my contributing file was a little thin, and I was trying to think of what else I could add. I'll close this issue for now, but let me know if you have any suggestions!
