### ISSUE TITLE
JavaScript errors when importing a tree

### ISSUE THREAD

**Issue by kinow** [chchch/sanskrit-alignment#2]
Hi @chchch 

I used the web interface, matrix-editor, with the example XML [c3.2.1-0.xml](https://github.com/chchch/sanskrit-alignment/blob/ab1a9a5b492f1738f36a375150b4da3e014accd4/example/xml/c3.2.1-0.xml).

Then I loaded the tree XML [alternative-rooted-tree.xml](https://github.com/chchch/sanskrit-alignment/blob/ab1a9a5b492f1738f36a375150b4da3e014accd4/example/trees/alternative-rooted-tree.xml).

I simply picked the first file in the listing of XMLs, and ditto for the tree file. Without worrying about correctness. I expected the software would either validate the inputs and raise an error, or show me something.

This is about this item in the [review](https://github.com/openjournals/joss-reviews/issues/4022) checklist for the JOSS paper: "Functionality: Have the functional claims of the software been confirmed?".

Instead of seeing the tree as in the paper, all that I can see is the table, and some errors in the browser console.

![image](https://user-images.githubusercontent.com/304786/147204267-f136d6eb-aa44-4d2c-925e-976d475087c1.png)

-Bruno

**Comment by chchch** [comment]
Thanks, I just updated the example files, although I'm not sure why it would cause that error. From your screenshot, it looks like you're using an old version of the matrix editor somehow — are you using the version hosted on GitHub at https://chchch.github.io/sanskrit-alignment/matrix-editor/ ?

**Comment by chchch** [comment]
Ah, my fault, I think you used the link from the README, which is outdated.

**Comment by kinow** [comment]
> Ah, my fault, I think you used the link from the README, which is outdated.

Ah! I see. I have the matrix-editor locally too with `python -m http.server 8000` from its directory, but I didn't test trees with it.

Looks like it's working now! And since the link has been fixed, and the GH actions will test and then GH pages will be updated, this issue won't happen again for other users. Let's close it. Thanks @chchch !

![image](https://user-images.githubusercontent.com/304786/147295019-01c4c78e-0111-4037-b235-dfae5b86ebd3.png)
